RedisLabs/memtier_benchmark

- client.cpp
when running memtier_benchmark along with --client-stats the printed latency distributions are not actual latencies. Moreover, SET ops percentage are false ( greater than 100% and calculated using total_get_ops).
> save_csv does not report proper latency distribution

- CHANGES
- JSON_handler.cpp
- JSON_handler.h
- Makefile.am
- client.cpp
- client.h
- config_types.cpp
- config_types.h
- configure.ac
- file_io.cpp
- file_io.h
- item.cpp
- item.h
- memtier_benchmark.cpp
- memtier_benchmark.h
- obj_gen.cpp
- obj_gen.h
- protocol.cpp
- protocol.h
* Add JSON output support: add thin json handling class that could be
overridden for extensive uses
* Add --json-out-file: Name of JSON output file, if not set, will not
print to json
* Refactor some code duplications in the prints sections
* Change license to 2017
> add support for JSON output

- memtier_benchmark.cpp
Fixes the random problem originated by calling the random creation BEFORE setting the variable from the configuration.
> Fix random issue

- obj_gen.cpp
- obj_gen.h
Useful in case we want to make sure the dataset content is constantly changing during the benchmark.
Doesn't impact performance because only a single byte is modified in the buffer per write. On the other hand data isn't really random (but still more random than before).
> different values for each key when random data is set

- protocol.cpp
Prior to this fix
./memtier_benchmark -s localhost -p 11211 --protocol=memcache_binary -t 1 -c 1 --key-maximum=100 --pipeline=2 --hide-histogram
would fail, now it passes.
> Fix binary protocol pipelining: always use the actual body length.

- client.cpp
Added if (jsonhandler != NULL){ jsonhandler->close_nesting();} for making sure that Best, Worst and Average results will be brothers in the JSON
> Fix missing closing of JSON nesting for results printing

- Makefile.am
- README.md
- client.cpp
- client.h
- cluster_client.cpp
- cluster_client.h
- connections_manager.h
- memtier_benchmark.cpp
- memtier_benchmark.h
- obj_gen.cpp
- obj_gen.h
- protocol.cpp
- protocol.h
- shard_connection.cpp
- shard_connection.h
new 'cluster_client' add to support cluster mode.
the new client use CLUSTER_SLOTS command to retrive the
key-->node mapping, create separate connection fot each node,
and send the commands to the appropriate connection according
to hash calculation.
> add support for cluster mode

- CHANGES
- client.cpp
- client.h
- configure.ac
- connections_manager.h
- memtier_benchmark.cpp
- memtier_benchmark.h
- obj_gen.cpp
main issues were:
* --requests was only 32bit
* --key-pattern=P:P was incompatible with large keyspace
* random number generator was unfair (some of the upper bits were constant)
> fix 64bit keyspace problems and release 1.2.12

- client.cpp
- memtier_benchmark.cpp
- shard_connection.cpp
1. reslove address only when using server/port option and not unix-socket
2. disable runing cluster-mode with unix-socket, since even when using
unix-socket option in redis-server, the CLUSTER SLOTS command
return the local address and default port (6379) and not the unix domain socket.
> fix unix socket connection

- README.md
- client.cpp
- client.h
- memtier_benchmark.cpp
- memtier_benchmark.h
fix obj_iter_type() to return the appropriate
iterator for the set/get command, when using sequential pattern
> fix sequential key pattern

- CHANGES
- client.cpp
- configure.ac
1. when using parallel key-pattern each client get a subset of the key-range.
if the user also chooses the run-count option, the subset of each client exceeded
the configured key-range.
fix this bug and keep the subset of keys for each client to be in
range for each run.
2. fix the overlapping of the ranges when using parallel key-pattern.
> fix parallel key-pattern

- bash-completion/memtier_benchmark
- client.cpp
- client.h
- config_types.cpp
- config_types.h
- memtier_benchmark.cpp
- memtier_benchmark.h
- obj_gen.cpp
- obj_gen.h
- protocol.cpp
- protocol.h
- run_stats.cpp
- run_stats.h
- run_stats_types.cpp
- run_stats_types.h
- shard_connection.cpp
- shard_connection.h
this commit expand the ability of running arbitrary command
to enable runing multiple arbitrary commands by
adding the --command option for each command.
> add support for multiple arbitrary commands

- memtier_benchmark.cpp
when using the parallel key-pattern (P), it must be configured
for all commands (SET:GET or --command-key-patterns's)
> fix parallel key-pattern command line option

- Dockerfile
Optimize final image build size by grouping commands in the same build step and deleting unneeded package installation files. Add non-interactive env vars.
> Dockerfile optimizations

- JSON_handler.cpp
- JSON_handler.h
- client.cpp
- config_types.cpp
- config_types.h
- file_io.cpp
- file_io.h
- item.cpp
- item.h
- obj_gen.cpp
- obj_gen.h
- protocol.cpp
- protocol.h
- shard_connection.cpp
I removed trailing whitespaces in source code.
> remove unnecessary whitespaces

- memtier_benchmark.cpp
when using the arbitrary command with run count, the
format_arbitrary_command() called for each run, causing to
the data to be corrupted.
moving the function to be called once at main()
> fix issue #104 arbitrary command with run count

- memtier_benchmark.cpp
- memtier_benchmark.h
- shard_connection.cpp
Our setup uses SNI for routing, and this is a quick hack to include it as a command line option.
Feedback welcomed.
> Add SNI support

- shard_connection.cpp
disable the bufferevent only when connection state is 'connected'
> fix issue #108 cluster mode crash

- memtier_benchmark.cpp
init_openssl function is called only when tls is used:
`
#ifdef USE_TLS
// Initialize OpenSSL only if we're really going to use it.
if (cfg.tls) {
init_openssl();
`
Corresponding cleanup_openssl function is called whether or not tls is used hence we got a core:
`
Thread 1 "memtier_benchma" received signal SIGSEGV, Segmentation fault.
__GI___pthread_mutex_destroy (mutex=0x0) at pthread_mutex_destroy.c:30
30      pthread_mutex_destroy.c: Nie ma takiego pliku ani katalogu.
(gdb) where
#0  __GI___pthread_mutex_destroy (mutex=0x0) at pthread_mutex_destroy.c:30
#1  0x000055555555a1bd in cleanup_openssl_threads () at memtier_benchmark.cpp:1185
#2  cleanup_openssl () at memtier_benchmark.cpp:1204
#3  main (argc=<optimized out>, argv=<optimized out>) at memtier_benchmark.cpp:1587
`
This pull …
> Fixed core when tls is enabled but not used

- Dockerfile
Checking the Dockerfile, I've realized that the build is done using source code _downloaded_ from Github. Most of the Docker workflow advantages come from building the artifact from local Docker build context, especially the source code.
I've changed this, so now it makes more sense to have a Docker Compose manifest for local development (#88), since it will build from local source, too. Thus, anybody can start hacking right away without having to install anything else besides Docker and Docker Compose. Now it makes more sense, IMO.
> Dockerfile: Get source files from local build context instead of downloading from git

- README.md
Better promote https://hub.docker.com/r/redislabs/memtier_benchmark, so end users don't have to check Docker Hub or clone-and-build by themselves.
> Add example on using images from Docker Hub

- JSON_handler.cpp
- run_stats_types.cpp
Leads to compile issues on some platforms (e.g. FreeBSD), see #119.
> Fix: missing config.h includes in some files.

- cluster_client.cpp
- protocol.cpp
This also fixes the crashes reported in #116.
> Fix some memory issues.

- shard_connection.cpp
the fix disables the buffer-events (write/read) only when
the connection finished its activity completely (nothing to read
and nothing to write)
> fix issue #132, endless loop

- run_stats.cpp
- run_stats.h
- run_stats_types.cpp
- run_stats_types.h
Handle all allocation, deallocation and copying of hdr_histogram
automatically using a safe_hdr_histogram wrapper class.
This also saves the need for explicit initialization and custom
constructors.
> Fix memory leaks involving hdr_histogram.

- shard_connection.cpp
See https://github.com/RedisLabs/memtier_benchmark/issues/135
The fix is simple enough, we just abort if we detect this particular
setting.
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
> Prevents the program from entering endless loop

- obj_gen.cpp
in case we are using jrand48 and generate a random number, all the bits
(except for the last bit) are reset, instead of resetting only the last bit.
> fix issue #158, gaussian key-pattern on MAC OS

- run_stats.cpp
- run_stats.h
The current implementation collects stats in a std::vector. As the vector grows it needs to be resized, during long runs this resize can take significant amounts of time and appear to the user as though the server is not responding.  This is both inacurate and confusing to users using the tool.
The chart below clearly demonstrates the problem during a long run against redis.  You can see big dropouts around 208, 520, 2080, 4056 seconds, profiler shows this time is spent in memmove during a vector resize.
During the benchmark its critical that updating stats takes a constant time.  Otherwise the benchmark results will be skewed.  Because of this a std::vector with its O(n) insert is not the correct datastructure.  The fix changes the code to a std::list which can guarantee O(1) inserts …
> Fix dropouts due to vector resize during long benchmarks

- memtier_benchmark.cpp
Enable OpenSSL to load a configuration file using the standard openssl.cnf file. 
In this way, we can change the default OpenSSL ENGINE, as well as configure other capabilities. 
This aligns memtier benchmark to a similarly added capability in Redis here : https://github.com/redis/redis/pull/8143
By providing this capability to memtier benchmark, we can ensure that memtier benchmark and redis are using the same OpenSSL configuration (e.g. ENGINE) while performing a test.
> Enable OpenSSL to load a configuration file during initialization

- tests/test_requirements.txt
This allows a longer-tail migration to the latest version as each repository is ready, without breaking individual projects.
> Pinning rltest to the last release prior to redis-py 4 as a requirement

- obj_gen.cpp
The current logic for randomizing value_buffer looks like something's wrong, and I've tried to fix it.
I guess the original intent was to read the `/dev/urandom` file every `20*64*64` bytes, and I modified it to follow this logic.
Related issue #171.
> Correctly randomize value buffer

- .github/workflows/ci.yml
- .gitignore
- README.md
- tests/gen-test-certs.sh
- tests/include.py
- tests/run_tests.sh
- tests/tests_oss_simple_flow.py
This PR clarifies how to test memtier_benchmark locally and uses the exact same script for CI testing. 
Details on how to to test memtier:
The project includes a basic set of integration tests.
**Integration tests**
Integration tests are based on [RLTest](https://github.com/RedisLabsModules/RLTest), and specific setup parameters can be provided
to configure tests and topologies (OSS standalone and OSS cluster). By default the tests will be ran for all common commands, and with OSS standalone setup.
To run all integration tests in a Python virtualenv, follow these steps:
$ mkdir -p .env
$ virtualenv .env
$ source .env/bin/activate
$ pip install -r tests/test_requirements.txt
$ ./tests/run_tests.sh
To understand what test options are available simply run:
$ ./tests/run_tests.sh --help
> Moved integration testing logic out of github actions and included testing section on Readme

- cluster_client.cpp
- memtier_benchmark.cpp
- memtier_benchmark.h
- protocol.cpp
- protocol.h
- shard_connection.cpp
- shard_connection.h
- add new command line argument, '--resp', to send HELLO command
at the begining of a connection to set the RESP mode: 2 or 3.
- the redis protocol component updated to support the new RESP 3 types.
exceptional are:
- Push type: Maybe will be added on next phase, but need to understand better
how and what does it mean to benchmark Redis with push commands.
- Streamed strings & Streamed aggregated: Currently not used by Redis.
> add support for resp3

- run_stats.cpp
This PR brings more clarity to the issue described in #184 
Bottom line it now prints latencies to the microsecond granularity both on the summary, and histogram print
> Increased print precision of percentiles to single micro (before was 10 micros)

- run_stats.cpp
- run_stats.h
- run_stats_types.cpp
- run_stats_types.h
Fixes #157 . 
Instead of keeping the raw histograms per second, we keep the computed percentiles that we need to store at the end of the benchmark. 
Using @weisiw script to check the memory we can confirm that the issue is gone
> Fixed memory usage increasing over time due to per second histogram usage

- .github/workflows/ci.yml
The current version is broken as Python 3.6 is no longer available.
> Upgrade CI Python version.

- tests/include.py
- tests/tests_oss_simple_flow.py
Also do some minor cleanups around unused args.
> Always print out stderr/out output on test failures.

- tests/include.py
- tests/tests_oss_simple_flow.py
Up until now we didn't really checked the keyspace range after write tests. This PR introduces it. 
I noticed that due to the PR #206 having a but and precisely increasing the keyspace range.
> Include keyspace range checks on flow tests

- memtier_benchmark.cpp
I have fixed issue 211.
This changed key_stddev and key_median to read as unsigned long long.
In real-world use cases, the key ranges will be wide enough that the fractional portions will not matter.
> Fix issue #211. Allow key_stddev and key_median options to be set values

- .github/workflows/ci.yml
Ubuntu 18.04 is no longer supported by GitHub.
> CI: bump Ubuntu runner version.

- client.cpp
- cluster_client.cpp
- config_types.cpp
- config_types.h
- memtier_benchmark.cpp
- memtier_benchmark.h
Add new --ipv4 (-4) and --ipv6 (-6) command line options to force address resolution.
The default value is unspecified, and we will try resolving both.
> Support forcing of IPv4/IPv6 resolution.

- .github/workflows/dockers.yml
It appears that github actions did not kick off, due to the inclusion of a tags specifier, in the push definition. This PR removes that.
Similarly, it appears that this is somehow not merged into master, though the git log shows it is. Hence, the PR.
> Restoring docker build

- shard_connection.cpp
In cluster mode, where there are few requests with many shards, some of the shards might not send any requests.
Currently, the memtier-benchmark is hang, because the connections to these shards are not disabling their read/write events
> Issue #204, Disable READ/WRITE events if no requests sent

- shard_connection.cpp
When a connection is dropped, it needs to empty its pipeline of pending responses, so in case of reconnection, it won't hang waiting for old requests.
> Issue #94, test hangs in cluster mode

- .github/workflows/ci.yml
- config_types.cpp
- memtier_benchmark.cpp
- memtier_benchmark.h
- tests/include.py
By default it will always try to use v1.2 and v1.3. 
It allows specifying multiple versions via comma delimiter. 
```
./memtier_benchmark   --cert ~/redislabs/redis/tests/tls/redis.crt     --key ~/redislabs/redis/tests/tls/redis.key --cacert ~/redislabs/redis/tests/tls/ca.crt  -c 1 -t 1 --tls --hide-histogram --tls-protocols tlsv1.1,tlsv1.2
```
Confirmation of data capture that indeed we're using v1.2:
```
./memtier_benchmark   --cert ~/redislabs/redis/tests/tls/redis.crt     --key ~/redislabs/redis/tests/tls/redis.key --cacert ~/redislabs/redis/tests/tls/ca.crt  -c 1 -t 1 --tls --hide-histogram --tls-protocols tlsv1.3
```
Confirmation of data capture that indeed we're using v1.3:
```
$ ./memtier_benchmark   --cert ~/redislabs/redis/tests/tls/redis.crt     --key …
```
> Enable specifying the tls protocol version to use via --tls-protocols argument

- memtier_benchmark.cpp
Fixes #235 
nullptr was introduced in c++11 and if your compiler does not support it will happen the error of #235 . This PR addresses it.
Reference: https://www.stroustrup.com/bs_faq2.html#null
> Avoid c++11 nullptr and use 0 on null comparison

- memtier_benchmark.cpp
- memtier_benchmark.h
- shard_connection.cpp
- shard_connection.h
- tests/include.py
- tests/tests_oss_simple_flow.py
A new 'rate-limiting' option was added to control the number of request per second.
The rate limiting is based on the 'Token Bucket' algorithm, and according to the configured rate, on each interval, a "new" amount of requests allowed to be sent to the server.
The rate-limiting is at the connection level. Therefore, in cluster mode, the limitation is for each shard, so if, for example, the cluster has three shards and the user configured one request per second. On every second, memtier-benchmark will send three requests, one for each shard.
> Add rate limiting to control the number of requests per second

- client.cpp
- client.h
- cluster_client.cpp
- memtier_benchmark.cpp
- obj_gen.cpp
- obj_gen.h
- shard_connection.cpp
- shard_connection.h
- tests/data-import-2-keys-expiration.txt
- tests/data-import-2-keys.txt
- tests/include.py
- tests/run_tests.sh
- tests/tests_oss_simple_flow.py
The PR includes some refactoring and cleanup around the following:
object_generator
- generate_key(), a new function that generates a key and stores it
inside internal buffer (no need for a buffer at client level)
import_object_generator
- Align it to object_generator APIs of getting key/value/expire
- read_next_item - new function for reading the next item before
creating SET command
- read_next_key - new function for reading (pointing) to the next
key before creating the GET command
data_object
- Removed.
We were already getting key/value/expire separately. Now that
data-import and verify-data also moved to do it like that,
we could remove it completely.
verify_client
- Unify the craate_request with its base class, and derive the
create_x_request functions.
> see #238, data import broken

- README.md
This PR includes documentation on why/when you should use a rate-limited benchmark, and provides one example of it in the readme for simpler comprehension.
> Include rate-limiting Readme section

- .github/workflows/ci.yml
- memtier_benchmark.cpp
The current master as of 9ddfcff fails to build without TLS.
It seems that changes from bec3471f were not guarded by the correct macro.
```
memtier_benchmark.cpp:320:15: error: no member named 'tls_protocols' in 'benchmark_config'
320 |     if (!cfg->tls_protocols)                                               
|          ~~~  ^                                                            
memtier_benchmark.cpp:321:14: error: no member named 'tls_protocols' in 'benchmark_config'
321 |         cfg->tls_protocols = REDIS_TLS_PROTO_DEFAULT;                      
|         ~~~  ^                                                             
memtier_benchmark.cpp:321:30: error: use of undeclared identifier 'REDIS_TLS_PROTO_DEFAULT'
321 |         cfg->tls_protocols = REDIS_TLS_PROTO_DEFAULT; …
```
> Fix upstream missing USE_TLS macro guard

- client.cpp
- cluster_client.cpp
- run_stats.cpp
- run_stats.h
- run_stats_types.cpp
- run_stats_types.h
- tests/include.py
- tests/tests_oss_simple_flow.py
The following PR:
- List ingress and egress separately on JSON and CSV exports. 
- Include overall BW results in the JSON and CSV and also raw values per second in the JSON timeseries
- This PR is backwards compatible on the JSON output
excerpt from the json output showcasing the added overall metrics ("KB/sec RX/TX", "KB/sec RX", "KB/sec TX") and the per second ones ("Bytes RX","Bytes TX")
```
,"Gets":{
"Count": 2000000
,"Ops/sec": 311352.91
,"Hits/sec": 311352.91
,"Misses/sec": 0.00
,"Latency": 0.643
,"Average Latency": 0.643
,"Min Latency": 0.008
,"Max Latency": 5.183
,"KB/sec": 20922.58
,"KB/sec RX/TX": 20922.58
,"KB/sec RX": 11858.17
,"KB/sec TX": 9064.41
,"Time-Serie":{
"0":{
"Bytes RX": 12263160
,"Bytes TX": 9372271
,"Count": 314440
(...)
(...)
```
> List ingress and egress separately on JSON and CSV exports. Include BW and also raw values per second

- configure.ac
- memtier_benchmark.cpp
- shard_connection.cpp
- Fixes #247 
- I've set an old standard to make this work even for old compiler versions. Agree @YaacovHazan and @yossigo ?
> Fixed deprecated and casting build errors caught on recent compilers

- .github/workflows/ci.yml
- README.md
- memtier_benchmark.cpp
This PR:
- Fixes https://github.com/RedisLabs/memtier_benchmark/issues/235
- Introduces an CI check for openssl v1.0.2 build. 
Reproduced via:
```
brew install rbenv/tap/openssl@1.0
autoreconf -ivf
PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.0/lib/pkgconfig" ./configure
make
```
error:
```
(base) fco@fcos-Air memtier_benchmark % make
make  all-am
make[1]: Entering directory '/Users/fco/redislabs/memtier_benchmark'
CXX      memtier_benchmark-memtier_benchmark.o
memtier_benchmark.cpp:328:16: warning: variable 'ignore' set but not used [-Wunused-but-set-variable]
size_t ignore = fread(&R, sizeof(R), 1, f);
^
memtier_benchmark.cpp:1396:50: error: use of undeclared identifier 'SSL_OP_NO_TLSv1_3'
SSL_CTX_set_options(cfg.openssl_ctx, SSL_OP_NO_TLSv1_3);
^
1 warning and 1 error generated. …
```
> Fixed build for tls v1.3 on openssl v1.0.2. Added CI check

- .github/workflows/ci.yml
- shard_connection.cpp
- tests/tests_oss_simple_flow.py
> Use SO_LINGER with timeout 0 to avoid thousands of server sockets in TIME_WAIT when using small reconnect intervals

- .gitattributes
Adding this file will ensure text files are checked out on all dev systems as LF, which is **required** for this project to build correctly.
As mentioned in #163, if you check out this project on a Windows system and try to `docker build`, you'll get:
```
7.187 configure: creating ./config.status
.in'7 config.status: error: cannot find input file: `
```
I determined this is because text-based files **that are expected to be LF at build time** are being automatically checked out as CRLF on Windows machines. When those CRLF files are copied over to a Linux-based Docker context at build time, they cause the build to blow up. After renormalizing all text files as LF, the build succeeds as expected.
This change will ensure all contributors, no matter the dev OS, will be able to work with this …
> Add .gitattributes file for better behavior on Windows-based systems

- JSON_handler.cpp
- deps/hdr_histogram/hdr_histogram.c
- deps/hdr_histogram/hdr_histogram.h
- run_stats.cpp
- run_stats_types.cpp
- run_stats_types.h
- tests/run_tests.sh
- tests/tests_oss_simple_flow.py
We can reproduce easily with:
```
memtier_benchmark --command "DEBUG SLEEP 2" --json-out-file 2secs.json -n 10 -c 1 -t 1
```
To confirm the issue is fixed, we've added a test that previously generated bad JSON.
```
TEST=tests_oss_simple_flow:test_valid_json_using_debug_command VERBOSE=1 ./tests/run_tests.sh
```
old output:
```
{
"configuration":{
"server": "localhost"
,"port": 6379
,"unix socket": "(null)"
,"address family": "Unspecified"
,"protocol": "redis"
,"out_file": "(null)"
,"tls": "false"
,"cert": "(null)"
,"key": "(null)"
,"cacert": "(null)"
,"tls_skip_verify": "false"
,"sni": "(null)"
,"client_stats": "(null)"
,"run_count": 1
,"debug": 0
,"requests": 3
,"rate_limit": 0
,"clients": 1
,"threads": 1
,"test_time": 0
,"ratio": "1:10"
,"pipeline": 1
,"data_size": 32
,"data_offset": 0 …
```
> Ensuring we produce a valid JSON in case of empty string and -nan

- .github/workflows/release.yml
This PR updates the GitHub Actions workflow to use v4 of actions/upload-artifact and actions/download-artifact, following the [deprecation](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/) and [migration guidelines](https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md) outlined in the respective repositories.
> Migrate to v4 of actions/upload-artifact and actions/download-artifact

- .github/workflows/release.yml
On smoke test step of release action, we now need to properly specify which artifacts to download. 
On the previous change we've missed to properly populate the build arch. This PR addresses it.
>  Fixed artifact download and upload steps to match v4 requirements 

- .github/workflows/release.yml
This PR enables to trigger the same process of the release workflow up until the moment we do the last step.
> Enabled a workflow dispatch to smoke test the release process.

- .github/workflows/ci.yml
- .github/workflows/release.yml
Following the error in: https://github.com/RedisLabs/memtier_benchmark/actions/runs/11958405087/job/33340558967
```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
we can see in https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ node12 is deprectated and node16 as well. 
We should bump checkout actions from v2 to v4 to solve this.
According to https://github.com/actions/runner-images/blob/macos-14-arm64/20241119.509/images/macos/macos-14-arm64-Readme.md
> [macOS] OpenSSL 1.1 will be removed and OpenSSL 3 will be the default for all macOS images from November 4, 2024
so we  use macos-12 which does not have the deprecation notice and won't fail.
> GH actions deprecation fixes: migrate checkout github action from v2 to v4 and openssl@1.1/1.0 fixes.

- .github/workflows/ci.yml
- .github/workflows/release.yml
To ensure we validate some of the steps of the release we're now testing with the SMOKE_TEST_IMAGES on CI and not only on release.
Sample of focal failure due focal check v4 issue:
https://github.com/RedisLabs/memtier_benchmark/actions/runs/11999571766/job/33447645699
fixed on v3 being used only for focal:
https://github.com/RedisLabs/memtier_benchmark/actions/runs/11999864960/job/33448272461?pr=282
> Testing ubuntu and debian builds on CI. all v1/v2 actions to v4 migrated

- shard_connection.cpp
When a connection disconnected, the timer event was not free, and cause the test to keep running forever.
One of these cases is when we are starting the benchmark in cluster-mode and using the replica's ip/port.
> Issue #285, Fix rate-limiting with cluster-mode

- .github/workflows/ci.yml
from worfklow: https://github.com/RedisLabs/memtier_benchmark/actions/runs/12622199253/job/35169853336?pr=286 
> Annotations
2 errors
GitHub Actions has encountered an internal error when running your job.
The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721
To address this we're switching to macos-13 which still has openssl 1.1 according to https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
> macOS-12 environment is deprecated. Switching actions to macOS-13

- .github/workflows/ci.yml
CI on memtier is failing [reference failure](https://github.com/RedisLabs/memtier_benchmark/actions/runs/12734599388/job/35492362676) but due to ubuntu 24.04 support (they should have changed ubuntu:latest to it). 
Related to lcov >= 2.0 version check. To fix it we should do coverage checks on Ubuntu 22.04 instead of latest. 
On 24.04 we have:
```
Get:42 http://azure.archive.ubuntu.com/ubuntu noble/universe amd64 lcov all 2.0-4ubuntu2 [223 kB]
```
and we want:
```
checking for lcov version... invalid
configure: error: You must have one of the following versions of lcov: 1.6 1.7 1.8 1.9 1.10 1.11 1.12 1.13 1.14 1.15 1.16 (found: /etc/lcovrc).
Error: Process completed with exit code 1.
```
reference happening to others:
https://github.com/autoconf-archive/autoconf-archive/pull/298#issuecomme …
> Doing coverage checks on Ubuntu 22.04 instead of latest due to autoconf lcov >= 2.0 issue

- deps/hdr_histogram/hdr_histogram.c
- deps/hdr_histogram/hdr_histogram.h
- run_stats.cpp
- run_stats.h
- run_stats_types.cpp
- run_stats_types.h
Fixes #294 
It also updates the hdr histogram dependency to make usage of 2 optimizations we've added there quite a while ago:
- https://github.com/HdrHistogram/HdrHistogram_c/pull/90
- https://github.com/HdrHistogram/HdrHistogram_c/pull/94
Altogether, we've reverted the regression introduced in v2.1.1 and also reduced by 22% the CPU usage for the same QPS (even a bit higher). 
Sample benchmark command:
```
./memtier_benchmark --hide-histogram --pipeline=1 -c 100 -t 100 -d 1000 --key-maximum=9625503 --key-pattern=R:R --ratio=1:0  --test-time=60
```
CPU usage fix and improvement (red is this PR) :
Ops/sec fix and improvement (red is this PR) :
> Revert LATENCY_HDR_SEC_SIGDIGTS to 2. Optimize summarize_current_second by using hdr_value_at_percentiles() instead of N x hdr_value_at_percentile().

- .github/workflows/release.yml
Fixes issue detected on 2.1.4 release process: https://github.com/RedisLabs/memtier_benchmark/actions/runs/13049336672/job/36405897176
we're already using it in normal CI flows: https://github.com/RedisLabs/memtier_benchmark/blob/master/.github/workflows/ci.yml#L33
> Use libpcre3-dev on apt release flow

- .github/workflows/release.yml
- we were able to reproduce the error from   https://github.com/RedisLabs/memtier_benchmark/actions/runs/13053957118/job/36420569728 in https://github.com/RedisLabs/memtier_benchmark/actions/runs/13237772497/job/36946536026?pr=299 and fix it. 
- Ensure that if we're on a release action that the release version matches the one in the code/artifacts.
> Test build source package, build binary package and smoke test on CI.

- .github/workflows/release.yml
Fixes https://github.com/RedisLabs/memtier_benchmark/actions/runs/13265125990
> using ubuntu-22.04 on runner of release

- .github/workflows/ci.yml
- More info at https://github.com/actions/runner-images/issues/11101
> Remove ubuntu-20.04 from build-build matrix due to GH removal

- obj_gen.cpp
When I run `memtier_benchmark` with `--data-import` (including 500000 keys),  it took a long time to quit after benchmark finished. 
With pstack, I found the process was waiting in `~imported_keylist()`
```
...
#6  std::vector<imported_keylist::key*, std::allocator<imported_keylist::key*> >::erase (__position=..., this=0x1e685e8) at /usr/include/c++/9/bits/stl_vector.h:1428
#7  imported_keylist::~imported_keylist (this=0x1e685e0, __in_chrg=<optimized out>) at obj_gen.cpp:534
#8  0x0000000000407a1a in main (argc=<optimized out>, argv=<optimized out>) at memtier_benchmark.cpp:1641
```
`erase()` one by one for a dead vector wastes some time. So I replaced `erase()` with `clear()`, which makes it much faster.
> improve the performance of imported_keylist deconstruction

- config_types.cpp
- memtier_benchmark.cpp
- tests/tests_oss_zipfian_distribution.py
- tests/zipfian_benchmark_runner.py
This PR adds support for the Zipfian (Z) key access pattern to arbitrary commands in memtier_benchmark. 
- Updates the CLI argument parsing and validation logic to accept Z as a valid key pattern, ensures proper initialization of Zipf-related parameters when used in either global or per-command configurations
- Introduces test coverage for Zipfian access patterns across various arbitrary commands (SET, GET, HSET, etc.).
> Enabled Zipfian key distribution for arbitrary commands.

- configure.ac
This PR bumps the version from **2.1.4** to **2.2.0** to include recent feature additions and improvements.
- Added option to print and save all results when running multiple test iterations (#298 by @Yuval-Ariel).
- Initial support for keys following Zipfian distribution (#166 by @lfsu-ali).
- Enabled Zipfian key distribution for arbitrary commands (#314 by @filipecosta90).
- Added `--uri` flag to `memtier_benchmark` (compatible with `redis-cli` and `redis-benchmark` URI parsing) (#311 by @filipecosta90).
- Improved deconstruction performance of `imported_keylist` (#239 by @DarrenJiang13).
- Fixed request handling issue (#307 by @maxb-io).
- Removed `ubuntu-20.04` from build matrix following GitHub deprecation (#309 by @paulorsousa).
- Added macOS installation instructions via Homebrew …
> Bumping version to 2.2.0

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- Dockerfile.alpine
- README.md
- configure.ac
- debian/control
Fixes #315 
This PR removes the libpcre3-dev / pcre dependency across the project since it is no longer required for building or running memtier_benchmark.
Changes include:
- Dropped libpcre3-dev from CI workflows, Dockerfiles, and Debian packaging.
- Updated configure.ac to stop checking for pcre.
- Cleaned up README.md and installation instructions to reflect updated requirements.
- Including debian build checks on CI.
> Remove libpcre3-dev dependency from build and CI
