memtier_benchmark.cpp
(as described in the individual commits' messages)
=> small improvements to '--help'

client.cpp, client.h, cluster_client.cpp, cluster_client.h, shard_connection.cpp, shard_connection.h
when using cluster mode, "-ASK ..." response can return from
cluster.
adding support to handle ASK reply.
=> support ASK in cluster mode

.gitignore, Makefile.am, bash-completion/memtier_benchmark, configure.ac
add bash completion for memtier-benchmark
=> add bash completion script

README.md, config_types.h, configure.ac, memtier_benchmark.cpp, protocol.h
=> Fix and clean up build on macOS.

README.md
githalytics looks dead, so for now let's remove the link from readme
=> Remove githalytics from README.md

Dockerfile, memtier_benchmark.cpp
* Fix compatibility with older OpenSSL versions.
* Fix missing Dockerfile dependency.
=> Fix TLS build issues.

shard_connection.cpp
add missing bufferevent_disable for connections that
complete to send new requests
=> fix issue #94 cluster mode stuck

memtier_benchmark.cpp
OpenSSL 1.0.2 and older require expicit locking callbacks in order to be
thread safe. Without this fix, using TLS and multiple threads on older
versions of OpenSSL would result with crashes/unexpected behavior.
=> Fix OpenSSL <1.1.0 threads setup.

shard_connection.cpp
the issue relates to the way each connection disable its events
move that code to one place and handle it separately for read/write
=> fix issue #128 zeros in ouptut

protocol.cpp
the issue relates to wrong parsing of response
with zero size ($0\r\n\r\n), that doesn't handle
correctly the last CRLF.
=> fix issue #133, error when using --data-offset

memtier_benchmark.cpp
Related issue https://github.com/RedisLabs/memtier_benchmark/issues/139
TIL about Linux's [optarg](https://man7.org/linux/man-pages/man3/getopt.3.html).
=> Add -V as short for --version

README.import
To avoid unnecessary error while parsing data file through --import-data.
=> Added extra note to avoid unnecessary error

README.md
=> A few build instructions clarifications.

.github/workflows/release.yml, configure.ac, debian/changelog, debian/control, debian/copyright, debian/setup_sbuild.sh, debian/watch, memtier_benchmark.cpp, utils/prepare_release.sh
* Add GitHub workflow for building and publishing artifacts.
* Debian packaging related cleanups.
* Add prepare_release script to set up autoconf version and refresh
manual page.
=> Binary release workflow.

memtier_benchmark.cpp
=> TLS: Support chain certs in --cert.

README.md
- Updated company name and link on Readme.md
- Include license, release, and code coverage badges
=> Include license, release, and code coverage badges

dockers.yml
In theory, combining this directory structure with the existing webhook should publish a docker. Ideally we might extend the dockerhub build side.
=> Supporting multi platform dockers

.github/workflows/dockers.yml
* Remove unnecessary prints.
* Target repo is not hard coded.
=> Minor dockers workflow cleanup.

.github/workflows/dockers.yml, .github/workflows/release.yml
- Trigger dockers on release.
- Update ruby setup for deb-s3.
=> Fix release workflows.

client.cpp, run_stats.cpp, run_stats.h, run_stats_types.cpp, run_stats_types.h, tests/tests_oss_simple_flow.py
- Fixes #250 
- Fixes #249 
Included tests to cover both bugs
=> Fixed last second metric rolling. Fixed totals json section missing the latency quantiles

.github/workflows/release.yml
Related to https://github.com/RedisLabs/memtier_benchmark/actions/runs/11955868395/job/33329702115
=> Don't upload release assets if in workflow_dispatch

configure.ac
=> Bump version to 2.1.3

.github/workflows/release.yml
Addressed https://github.com/RedisLabs/memtier_benchmark/actions/runs/13265607587
=> Remove ubuntu:bionic logic from smoke-test-packages and removed usage of actions/download-artifact@v3.
